name: Linux
env:
  APP_NAME: "notepad"
  APP_PLATFORM: "linux"
  APP_ARCH: "x86_64"
  QT_VERSION: "6.7.0"

on:
  push:
    branches:
      - master

jobs:
  linux:
    name: Linux (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
      fail-fast: false
    steps:
      - name: Git Clone
        uses: actions/checkout@v4

      - name: Setup Qt6
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: "linux"
          target: "desktop"
          install-deps: "true"
          cache: "false"

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Install
        run: |
          cd build
          sudo make install
