name: Windows
env:
  APP_NAME: "notepad"
  APP_PLATFORM: "win32"
  APP_ARCH: "x64"
  QT_VERSION: "6.2.3"

on:
  push:
    branches:
      - master

jobs:
  win:
    name: Windows (windows-latest)
    runs-on: windows-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v3

      - name: Setup Qt6
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VERSION }}
          host: "windows"
          target: "desktop"
          install-deps: "true"
          cached: "false"

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
          windeployqt --no-translations Release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APP_NAME }}-${{ env.APP_PLATFORM }}-${{ env.APP_ARCH }}
          path: build\Release
